# Generated by Django 4.2.4 on 2023-08-21 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extensions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subsequentpermitremarks',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_permit_remark_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsequentpermitremarks',
            name='subsequent_permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_permit_remarks', to='extensions.subsequentpermit'),
        ),
        migrations.AddField(
            model_name='subsequentpermitremarks',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_permit_remark_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsequentpermitpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_permit_payment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsequentpermitpayment',
            name='subsequent_permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_payments', to='extensions.subsequentpermit'),
        ),
        migrations.AddField(
            model_name='subsequentpermitpayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_permit_payment_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsequentpermit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_permit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsequentpermit',
            name='enquirie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='extensions.enquiry'),
        ),
        migrations.AddField(
            model_name='subsequentpermit',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsequentpermit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_permit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualarrears',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_arrears', to='extensions.enquiry'),
        ),
        migrations.AddField(
            model_name='individualarrears',
            name='subsequent_permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_permit_arrears', to='extensions.subsequentpermit'),
        ),
        migrations.AddField(
            model_name='enquiryremarks',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remarks_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiryremarks',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_remarks', to='extensions.enquiry'),
        ),
        migrations.AddField(
            model_name='enquiryremarks',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remarks_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquirypayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_payment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquirypayment',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_payments', to='extensions.enquiry'),
        ),
        migrations.AddField(
            model_name='enquirypayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_payment_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='arrival_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ports_of_entry', to='extensions.portofentry'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquire_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marital_statuses', to='extensions.maritalstatus'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquire_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
