# Generated by Django 4.2.4 on 2023-08-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-arrival_date']},
        ),
        migrations.AddField(
            model_name='enquiry',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='enquiry_images'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='arrival_place',
            field=models.ForeignKey(help_text='Air/Sea Port', on_delete=django.db.models.deletion.PROTECT, related_name='ports_of_entry', to='extensions.portofentry'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='arrived_via',
            field=models.CharField(help_text='Straight flight/Last stop off', max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='validity',
            field=models.DateField(help_text='Ticket valid until', verbose_name='valid until'),
        ),
    ]
