# Generated by Django 4.2.4 on 2023-08-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0003_alter_enquiry_options_enquiry_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiryremarks',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='enquiry',
            name='exemption',
            field=models.FileField(blank=True, null=True, upload_to='exemption_images/'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='host_id',
            field=models.FileField(blank=True, null=True, upload_to='host_id_images/'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='host_id_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='host ID number'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='hotel_res',
            field=models.FileField(blank=True, null=True, upload_to='hotel_res_images/'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='passport_images'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='perm_res',
            field=models.BooleanField(default=False, verbose_name='permanent resident'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='rental_agreement',
            field=models.FileField(blank=True, null=True, upload_to='rental_agreement_images/'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='tempt_res',
            field=models.BooleanField(default=False, verbose_name='temporary resident'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='work_permit',
            field=models.FileField(blank=True, null=True, upload_to='work_permit_images/'),
        ),
    ]
