# Generated by Django 4.2.4 on 2023-08-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0004_alter_enquiryremarks_options_enquiry_exemption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='enquiry_images', verbose_name='photo'),
        ),
    ]
