# Generated by Django 4.2.4 on 2023-08-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0005_alter_enquiry_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='host_id',
            field=models.FileField(blank=True, null=True, upload_to='host_id_images/', verbose_name='Host ID'),
        ),
    ]
