# Generated by Django 4.2.4 on 2023-08-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0007_alter_enquiry_hotel_res'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsequentpermit',
            old_name='enquirie',
            new_name='enquiry',
        ),
    ]
