# Generated by Django 4.2.4 on 2023-08-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0008_rename_enquirie_subsequentpermit_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsequentpermitpayment',
            name='subsequent_permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_permit_payments', to='extensions.subsequentpermit'),
        ),
    ]
