# Generated by Django 4.2.4 on 2023-09-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0010_paymenttype_alter_enquirypayment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsequentpermit',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_permits', to='extensions.enquiry'),
        ),
    ]
