# Generated by Django 4.2.4 on 2023-09-04 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0011_alter_subsequentpermit_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsequentpermitpayment',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_permit_payment_types', to='extensions.paymenttype'),
        ),
    ]
