# Generated by Django 4.2.6 on 2023-10-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0013_portofentry_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofentry',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
