# Generated by Django 4.2.6 on 2023-10-29 20:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extensions', '0014_alter_portofentry_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnquiryRemarks',
            new_name='EnquiryRemark',
        ),
        migrations.RenameModel(
            old_name='SubsequentPermitRemarks',
            new_name='SubsequentPermitRemark',
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-arrival_date'], 'verbose_name_plural': 'enquiries'},
        ),
    ]
