# Generated by Django 4.2.6 on 2023-10-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0015_rename_enquiryremarks_enquiryremark_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualarrears',
            options={'verbose_name_plural': 'individual arrears'},
        ),
        migrations.AlterModelOptions(
            name='maritalstatus',
            options={'verbose_name_plural': 'marital statuses'},
        ),
        migrations.AlterModelOptions(
            name='portofentry',
            options={'verbose_name_plural': 'Ports of entry'},
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='means_of_support',
            field=models.CharField(choices=[('Personal Savings', 'Personal Savings'), ('Sponsorship', 'Sponsorship'), ('Employment', 'Employment'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='pov',
            field=models.CharField(choices=[('Tourism', 'Tourism'), ('Business', 'Business'), ('Education', 'Education'), ('Medical Treatment', 'Medical Treatment'), ('Family Visit', 'Family Visit'), ('Other', 'Other')], max_length=255, verbose_name='purpose of visit'),
        ),
    ]
