# Generated by Django 4.2.6 on 2023-10-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0016_alter_individualarrears_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='imm_offr',
        ),
    ]
